### ISSUE TITLE
Use GridFS to store large files

### ISSUE THREAD

**Issue by maugenst** [ThalKod/DropIt#58]
Hi...
As I read your code and stumbled about the 20mb size limit I also read about it on how to store files in a mongodb using gridfs. It seems that using gridfs would automatically break this barrier which "should" be 16mb from my pov(?). 
So, what do you think about using this instead of plain store the file as a documents in a schema?
Best regards,
Marius

Resources:
https://docs.mongodb.com/manual/core/gridfs/
https://www.mongodb.com/blog/post/building-mongodb-applications-binary-files-using-gridfs-part-1?jmp=docs 
https://www.npmjs.com/package/mongoose-gridfs

**Comment by ThalKod** [comment]
I'll look into it.

**Comment by maugenst** [comment]
Hm... Any update on this?

**Comment by ThalKod** [comment]
@maugenst I look at Gridfs and yes it's for storing files in mongo in chunk... Actually with the current design i'm not storing the file in plain store as a document in a schema but i'm storing his name, path etc.. There's actually no upload limit, i put the 20mb limit just because my server size is limited and i don't want to get big files.
